[package]
name = "tars"
version = "0.1.1"
license = "MIT"
authors = ["Hugues Gaillard <hugues.gaillard@me.com>"]
description = """
A Rust library providing useful technical indicators.
"""
keywords = [ "ta", "analysis", "trading", "algorithm", "indicator" ]
readme = "README.md"

[dependencies]